# Generated by Django 4.2 on 2023-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TareaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
