# Generated by Django 4.2 on 2023-05-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TareaApp', '0002_tarea_archivo_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Completado',
            field=models.BooleanField(default=False),
        ),
    ]
